on:
  workflow_dispatch: {}
  pull_request_target: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 8 16 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci --disable-nosem --disable-version-check --json --no-rewrite-rule-ids --no-suppress-errors --optimizations all --sarif-output semgrep.sarif.json
